ALTER TABLE memes ADD COLUMN auto_retries INT NOT NULL DEFAULT 0;
ALTER TABLE memes ADD COLUMN hidden_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE channels ADD COLUMN filtered INT NOT NULL DEFAULT 0;
